
GET https://localhost:5001/odata/category



###

GET https://localhost:5001/odata/category?$expand=products



###

POST https://localhost:5001/odata/category 
Content-Type: application/json

{
    "Name": "Deneme 2"
}


###

PUT https://localhost:5001/odata/category(3)
Content-Type: application/json

{
    "Name": "Deneme 1a"
}



###

DELETE https://localhost:5001/odata/category(4)
Content-Type: application/json

