
GET https://localhost:5001/odata/category



###

GET https://localhost:5001/odata/category?$expand=products



###

POST https://localhost:5001/odata/category 
Content-Type: application/json

{
    "Name": "Deneme 2"
}




###
# Add Category with Products
POST https://localhost:5001/odata/category 
Content-Type: application/json

{
    "Name": "Deneme 3",
    "Products": [
        {"Name": "Deneme Ürünü 3 A"},
        {"Name": "Deneme Ürünü 3 B"},
        {"Name": "Deneme Ürünü 3 C"},
        {"Name": "Deneme Ürünü 3 D"}
    ]
}



###

PUT https://localhost:5001/odata/category(3)
Content-Type: application/json

{
    "Name": "Deneme 1a"
}


###

PATCH https://localhost:5001/odata/category(3)
Content-Type: application/json

{
    "Name": "Deneme 1"
}



###

DELETE https://localhost:5001/odata/category(4)
Content-Type: application/json





###

POST https://localhost:5001/odata/product 
Content-Type: application/json

{
    "CategoryId": 1,
    "Name": "Deneme Ürünü 1"
}



###

POST https://localhost:5001/odata/product 
Content-Type: application/json

{
    "Category": {
        "Name": "Deneme Ürün Kategorisi"
    },
    "Name": "Deneme Ürünü 2"
}




###

PUT https://localhost:5001/odata/product(10)
Content-Type: application/json

{
    "CategoryId": 1,
    "Name": "Deneme Ürünü 3 E"
}


###

PUT https://localhost:5001/odata/product(10)
Content-Type: application/json

{
    "Category": {
        "Name": "C1"
    },
    "Name": "Deneme Ürünü 3 F"
}











###

POST https://localhost:5001/odata/vendor 
Content-Type: application/json

{
    "Name": "Deneme 3"
}



###

PUT https://localhost:5001/odata/vendor(10)
Content-Type: application/json

{
    "Name": "Deneme 4"
}


###

PUT https://localhost:5001/odata/vendor(10)
Content-Type: application/json

{
    "Name": "Deneme 3",
    "CreatedAt" : "2020-01-01T01:23:45.678+03:00",
    "CreatedBy" : 10,
    "ModifiedAt" : "2020-01-01T01:23:45.678+03:00",
    "ModifiedBy" : 10
}
